p8105_hw2_jw3638
================

\##Problem 1 Clean pols-month.csv data: Break up the variable mon into
integer variables year, month, and day; replace month number with month
name; create a president variable taking values gop and dem, and remove
prez_dem and prez_gop; and remove the day variable.

``` r
pols =
  read_csv("data/fivethirtyeight_datasets/pols-month.csv") |>
  separate(mon, into = c("year", "month", "day"), sep = "-", convert = TRUE) |>
  mutate(
    month = month.name[month],
    year = as.integer(year),
    president = case_when(
      prez_gop == 1 ~ "gop",
      prez_dem == 1 ~ "dem"
    )
  ) |>
  select(-prez_dem, -prez_gop, -day)
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
#For nice display of data in knit doc:
knitr::kable(head(pols, 5))
```

| year | month    | gov_gop | sen_gop | rep_gop | gov_dem | sen_dem | rep_dem | president |
|-----:|:---------|--------:|--------:|--------:|--------:|--------:|--------:|:----------|
| 1947 | January  |      23 |      51 |     253 |      23 |      45 |     198 | dem       |
| 1947 | February |      23 |      51 |     253 |      23 |      45 |     198 | dem       |
| 1947 | March    |      23 |      51 |     253 |      23 |      45 |     198 | dem       |
| 1947 | April    |      23 |      51 |     253 |      23 |      45 |     198 | dem       |
| 1947 | May      |      23 |      51 |     253 |      23 |      45 |     198 | dem       |

Clean snp.csv data. Arrange according to year and month.

``` r
snp = 
  read_csv("data/fivethirtyeight_datasets/snp.csv") |>
  mutate(date = mdy(date)) |>
  separate(date, into = c("year", "month", "day"), sep = "-", convert = TRUE) |>
  mutate(
    month = month.name[month],
    year = as.integer(year)
  ) |>
  select(year, month, close)
```

    ## Rows: 787 Columns: 2
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
knitr::kable(head(snp, 5))
```

| year | month |   close |
|-----:|:------|--------:|
| 2015 | July  | 2079.65 |
| 2015 | June  | 2063.11 |
| 2015 | May   | 2107.39 |
| 2015 | April | 2085.51 |
| 2015 | March | 2067.89 |

Clean unemployment.csv data. Tidy it up so that it can be merged with
pols-month and csv: switch from “wide” to “long” format and label
formatting is consistent

``` r
unemployment = 
  read_csv("data/fivethirtyeight_datasets/unemployment.csv") |>
  pivot_longer(
    cols = Jan:Dec,
    names_to = "month",
    values_to = "unemployment_percentage"
  ) |>
  mutate(
    month = month.name[match(month, month.abb)],
    year = as.integer(Year)
  ) |>
  select(year, month, unemployment_percentage)
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
knitr::kable(head(unemployment, 5))
```

| year | month    | unemployment_percentage |
|-----:|:---------|------------------------:|
| 1948 | January  |                     3.4 |
| 1948 | February |                     3.8 |
| 1948 | March    |                     4.0 |
| 1948 | April    |                     3.9 |
| 1948 | May      |                     3.5 |

Merging: Join the pols-month into snp, and merge unemployment into
(pols-month in snp)

``` r
merge1 <- 
  left_join(pols, snp, by = join_by(year, month))
merge2 <- 
  left_join(merge1, unemployment, by = join_by(year, month)) |>
  select(year, month, president, close, unemployment_percentage, everything())

knitr::kable(head(merge2, 5))
```

| year | month | president | close | unemployment_percentage | gov_gop | sen_gop | rep_gop | gov_dem | sen_dem | rep_dem |
|---:|:---|:---|---:|---:|---:|---:|---:|---:|---:|---:|
| 1947 | January | dem | NA | NA | 23 | 51 | 253 | 23 | 45 | 198 |
| 1947 | February | dem | NA | NA | 23 | 51 | 253 | 23 | 45 | 198 |
| 1947 | March | dem | NA | NA | 23 | 51 | 253 | 23 | 45 | 198 |
| 1947 | April | dem | NA | NA | 23 | 51 | 253 | 23 | 45 | 198 |
| 1947 | May | dem | NA | NA | 23 | 51 | 253 | 23 | 45 | 198 |

Dataset 1: pols-month shows data from 1947 per month for gov_gop (the
number of republican governors on the associated date), rep_gop (”
representatives), gov_dem (“democratic governors), sen_dem (”democratic
senators), rep_dem (“democratic representatives), and president (both
republican and democratic presidents). Dataset 2: snp shows data from
2015 of the the closing values of the S&P stock index on the associated
date per month. Dataset 3: unemployment shows data from 1948 for
unemployment_percentage per month. Resulting dataset (merged): shows
data from 1947 with columns close, unemployment_percentage, gov_gop,
sen_gop, rep_gop, gov_dem, sen_dem, rep_dem per month.

\##Problem 2

``` r
#Upload and Read Mr. Trash Wheel excel file, omit non-data entries (rows with notes / figures; columns containing notes) using arguments in read_excel.
mr_trashwheels <- 
  read_excel("data/202509+TrashWheel_Collection_Data.xlsx", 
             sheet = "Mr. Trash Wheel",
             range = "A2:N710") |>
  janitor::clean_names() |>
  #Omit rows that do not include dumpster-specific data 
  filter(!is.na(dumpster)) |> 
  mutate(
    sports_balls = as.integer(round(sports_balls))  
  ) |>
  mutate(identity = "mr", 
    year = as.numeric(year)
  )
knitr::kable(head(mr_trashwheels, 5))
```

| dumpster | month | year | date | weight_tons | volume_cubic_yards | plastic_bottles | polystyrene | cigarette_butts | glass_bottles | plastic_bags | wrappers | sports_balls | homes_powered | identity |
|---:|:---|---:|:---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|:---|
| 1 | May | 2014 | 2014-05-16 | 4.31 | 18 | 1450 | 1820 | 126000 | 72 | 584 | 1162 | 7 | 0 | mr |
| 2 | May | 2014 | 2014-05-16 | 2.74 | 13 | 1120 | 1030 | 91000 | 42 | 496 | 874 | 5 | 0 | mr |
| 3 | May | 2014 | 2014-05-16 | 3.45 | 15 | 2450 | 3100 | 105000 | 50 | 1080 | 2032 | 6 | 0 | mr |
| 4 | May | 2014 | 2014-05-17 | 3.10 | 15 | 2380 | 2730 | 100000 | 52 | 896 | 1971 | 6 | 0 | mr |
| 5 | May | 2014 | 2014-05-17 | 4.06 | 18 | 980 | 870 | 120000 | 72 | 368 | 753 | 7 | 0 | mr |

``` r
#Upload and Read Professor Trash Wheel excel file, omit non-data entries (rows with notes / figures; columns containing notes) using arguments in read_excel.
professor_trashwheels <- 
  read_excel("data/202509+TrashWheel_Collection_Data.xlsx", 
             sheet = "Professor Trash Wheel",
             range = "A2:M123") |>
  janitor::clean_names() |>
  filter(!is.na(dumpster)) |>
  mutate(identity = "professor", 
    year = as.numeric(year)
  )
knitr::kable(head(professor_trashwheels, 5))
```

| dumpster | month | year | date | weight_tons | volume_cubic_yards | plastic_bottles | polystyrene | cigarette_butts | glass_bottles | plastic_bags | wrappers | homes_powered | identity |
|---:|:---|---:|:---|---:|---:|---:|---:|---:|---:|---:|---:|---:|:---|
| 1 | January | 2017 | 2017-01-02 | 1.79 | 15 | 1950 | 6080 | 19700 | 8 | 3100 | 15600 | 29.83333 | professor |
| 2 | January | 2017 | 2017-01-30 | 1.58 | 15 | 9540 | 11230 | 17600 | 14 | 5630 | 16700 | 26.33333 | professor |
| 3 | February | 2017 | 2017-02-26 | 2.32 | 18 | 8350 | 9210 | 12000 | 19 | 6430 | 12400 | 38.66667 | professor |
| 4 | February | 2017 | 2017-02-26 | 3.72 | 15 | 8590 | 1030 | 13000 | 21 | 5870 | 11030 | 62.00000 | professor |
| 5 | February | 2017 | 2017-02-28 | 1.45 | 15 | 7830 | 9950 | 16000 | 18 | 7450 | 15340 | 24.16667 | professor |

``` r
#Upload and Read Gwynns excel file, omit non-data entries (rows with notes / figures; columns containing notes) using arguments in read_excel.
gwynn_trashwheels <- 
    read_excel("data/202509+TrashWheel_Collection_Data.xlsx", 
             sheet = "Gwynns Falls Trash Wheel",
             range = "A2:L352") |>
  janitor::clean_names() |>
  filter(!is.na(dumpster)) |>
  mutate(
    identity = "gwynn", 
    year = as.numeric(year)
  )
knitr::kable(head(gwynn_trashwheels, 5))
```

| dumpster | month | year | date | weight_tons | volume_cubic_yards | plastic_bottles | polystyrene | cigarette_butts | plastic_bags | wrappers | homes_powered | identity |
|---:|:---|---:|:---|---:|---:|---:|---:|---:|---:|---:|---:|:---|
| 1 | July | 2021 | 2021-07-03 | 0.93 | 15 | 1200 | 360 | 3400 | 1800 | NA | 15.50000 | gwynn |
| 2 | July | 2021 | 2021-07-07 | 2.26 | 15 | 2000 | 240 | 3900 | 2200 | NA | 37.66667 | gwynn |
| 3 | July | 2021 | 2021-07-07 | 1.62 | 15 | 1800 | 270 | 2900 | 2400 | NA | 27.00000 | gwynn |
| 4 | July | 2021 | 2021-07-16 | 1.76 | 15 | 1000 | 180 | 2100 | 1800 | NA | 29.33333 | gwynn |
| 5 | July | 2021 | 2021-07-30 | 1.53 | 15 | 2100 | 240 | 4000 | 2700 | NA | 25.50000 | gwynn |

``` r
#Combine professor 1. Trash Wheel and Gwynnda datasets and 2. combine with the Mr. Trash Wheel dataset to produce a single dataset.
trashwheels <- bind_rows(mr_trashwheels, professor_trashwheels, gwynn_trashwheels)

#what was the total weight of trash collected by Professor Trash Wheel?
totalweightprof <- professor_trashwheels |>
  summarise(total_weight = sum(weight_tons, na.rm = TRUE))

#What was the total number of cigarette butts collected by Gwynnda in June of 2022?
tot_gwynn_cigbutts <- gwynn_trashwheels |>
  filter(year == 2022, month == "June") |>
  summarise(tot_gwynn_cigbutts = sum(cigarette_butts, na.rm = TRUE))

knitr::kable(head(trashwheels, 10))
```

| dumpster | month | year | date | weight_tons | volume_cubic_yards | plastic_bottles | polystyrene | cigarette_butts | glass_bottles | plastic_bags | wrappers | sports_balls | homes_powered | identity |
|---:|:---|---:|:---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|:---|
| 1 | May | 2014 | 2014-05-16 | 4.31 | 18 | 1450 | 1820 | 126000 | 72 | 584 | 1162 | 7 | 0 | mr |
| 2 | May | 2014 | 2014-05-16 | 2.74 | 13 | 1120 | 1030 | 91000 | 42 | 496 | 874 | 5 | 0 | mr |
| 3 | May | 2014 | 2014-05-16 | 3.45 | 15 | 2450 | 3100 | 105000 | 50 | 1080 | 2032 | 6 | 0 | mr |
| 4 | May | 2014 | 2014-05-17 | 3.10 | 15 | 2380 | 2730 | 100000 | 52 | 896 | 1971 | 6 | 0 | mr |
| 5 | May | 2014 | 2014-05-17 | 4.06 | 18 | 980 | 870 | 120000 | 72 | 368 | 753 | 7 | 0 | mr |
| 6 | May | 2014 | 2014-05-20 | 2.71 | 13 | 1430 | 2140 | 90000 | 46 | 672 | 1144 | 5 | 0 | mr |
| 7 | May | 2014 | 2014-05-21 | 1.91 | 8 | 910 | 1090 | 56000 | 32 | 416 | 692 | 3 | 0 | mr |
| 8 | May | 2014 | 2014-05-28 | 3.70 | 16 | 3580 | 4310 | 112000 | 58 | 1552 | 3015 | 6 | 0 | mr |
| 9 | June | 2014 | 2014-06-05 | 2.52 | 14 | 2400 | 2790 | 98000 | 49 | 984 | 1988 | 6 | 0 | mr |
| 10 | June | 2014 | 2014-06-11 | 3.76 | 18 | 1340 | 1730 | 130000 | 75 | 448 | 1066 | 7 | 0 | mr |

``` r
totalweightprof
```

    ## # A tibble: 1 × 1
    ##   total_weight
    ##          <dbl>
    ## 1         256.

``` r
tot_gwynn_cigbutts
```

    ## # A tibble: 1 × 1
    ##   tot_gwynn_cigbutts
    ##                <dbl>
    ## 1              18120

The three datasets, Mr, Professor, and Gwynn before combining looked
really similar after I cleaned them. They all have columns dumpster,
month, year, date, weight_tons, volume_cubic_yards, plastic_bottles,
polystyrene, cigarette_butts, glass_bottles, plastic_bags, wrappers,
homes_powered, identity (which is mr, professor, or gwynn). There were a
few columns that were inconsistent: Mr had sports_balls. The total
weight of trash collected by Professor Trash Wheel is 256 and the total
number of cigarette butts collected by Gwynnda in June of 2022 is 18120.
